{{- range .Values.projects -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "argocd" }}
spec: {{ toYaml .spec | nindent 2 }}
  destinations:
    - namespace: argocd
      server: "https://kubernetes.default.svc"
{{- end -}}
