{{- range .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "argocd" }}
spec: {{ toYaml .spec | nindent 2 }}
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    {{- if .spec.destinations -}}
      {{ toYaml .spec.destinations | nindent 4 }}
    {{- end }}
  namespaceResourceWhitelist:
  {{- range .spec.destinations }}
    - group: "*"
      kind: "*"
  {{- end }}
{{- end }}
